#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_TIMES_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_TIMES_H

#if ENABLE_SEASONAL_ENCOUNTERS

#define SEASONS_SUMMER 0
#define SEASONS_AUTUMN 1
#define SEASONS_WINTER 2
#define SEASONS_SPRING 3
#define SEASONS_DEFAULT SEASONS_SUMMER

#define SEASON_WILD_COUNT 2

#define SEASON_ENC_RATE 30
#define SEASON_SLOT_0 75
#define SEASON_SLOT_1 SEASON_SLOT_0 + 25
#define SEASON_SLOT_TOTAL SEASON_SLOT_1

// STATIC_ASSERT(SEASON_SLOT_1 != 100, SeasonSlotTotalNot100)

#endif

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_TIMES_H
