#ifndef GUARD_CONFIG_WILD_ENCOUNTER_TIMES_H
#define GUARD_CONFIG_WILD_ENCOUNTER_TIMES_H

#define ENABLE_DAY_NIGHT_ENCOUNTERS     TRUE
#define ENABLE_SEASONAL_ENCOUNTERS      TRUE

#endif // GUARD_CONFIG_WILD_ENCOUNTER_TIMES_H
